[Wed Oct 26 18:41:46.620318 2016] [:error] [pid 14013] /usr/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Wed Oct 26 18:41:46.620390 2016] [:error] [pid 14013]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Wed Oct 26 18:41:46.620945 2016] [:error] [pid 14013] /usr/lib/python2.7/site-packages/flask/exthook.py:71: ExtDeprecationWarning: Importing flask.ext.login is deprecated, use flask_login instead.
[Wed Oct 26 18:41:46.620952 2016] [:error] [pid 14013]   .format(x=modname), ExtDeprecationWarning
[Wed Oct 26 18:41:46.791434 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 18:41:46.791446 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 18:41:51.910250 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 18:41:51.910274 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 18:43:39.805764 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 18:43:39.805780 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 18:43:42.845770 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 18:43:42.845792 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 18:43:47.814131 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 18:43:47.814176 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 18:45:44.505318 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 18:45:44.505336 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 18:45:51.311430 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 18:45:51.311469 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 18:45:53.324361 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 18:45:53.324377 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 18:45:54.755842 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 18:45:54.755866 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 18:45:56.649570 2016] [:error] [pid 14013] [remote 10.194.75.104:84] [2016-10-26 18:45:56,647] ERROR in app: Exception on /login [POST]
[Wed Oct 26 18:45:56.649598 2016] [:error] [pid 14013] [remote 10.194.75.104:84] Traceback (most recent call last):
[Wed Oct 26 18:45:56.649601 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Oct 26 18:45:56.649602 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     response = self.full_dispatch_request()
[Wed Oct 26 18:45:56.649604 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Oct 26 18:45:56.649606 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     rv = self.handle_user_exception(e)
[Wed Oct 26 18:45:56.649616 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Oct 26 18:45:56.649618 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     reraise(exc_type, exc_value, tb)
[Wed Oct 26 18:45:56.649620 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Oct 26 18:45:56.649621 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     rv = self.dispatch_request()
[Wed Oct 26 18:45:56.649623 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Oct 26 18:45:56.649624 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Oct 26 18:45:56.649626 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 500, in decorated
[Wed Oct 26 18:45:56.649627 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     return f(*args, **kwargs)
[Wed Oct 26 18:45:56.649629 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/var/www/movien_dev/app/views.py", line 44, in login
[Wed Oct 26 18:45:56.649631 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     return oid.try_login(form.openid.data, ask_for=['nickname', 'email'])
[Wed Oct 26 18:45:56.649632 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 561, in try_login
[Wed Oct 26 18:45:56.649634 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     auth_request = consumer.begin(identity_url)
[Wed Oct 26 18:45:56.649635 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 353, in begin
[Wed Oct 26 18:45:56.649637 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     return self.beginWithoutDiscovery(service, anonymous)
[Wed Oct 26 18:45:56.649638 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 376, in beginWithoutDiscovery
[Wed Oct 26 18:45:56.649640 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     auth_req = self.consumer.begin(service)
[Wed Oct 26 18:45:56.649642 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 598, in begin
[Wed Oct 26 18:45:56.649643 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     assoc = self._getAssociation(service_endpoint)
[Wed Oct 26 18:45:56.649645 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 1163, in _getAssociation
[Wed Oct 26 18:45:56.649646 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     self.store.storeAssociation(endpoint.server_url, assoc)
[Wed Oct 26 18:45:56.649648 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 212, in storeAssociation
[Wed Oct 26 18:45:56.649649 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     tmp_file, tmp = self._mktemp()
[Wed Oct 26 18:45:56.649651 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 173, in _mktemp
[Wed Oct 26 18:45:56.649653 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     fd, name = mkstemp(dir=self.temp_dir)
[Wed Oct 26 18:45:56.649654 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib64/python2.7/tempfile.py", line 304, in mkstemp
[Wed Oct 26 18:45:56.649655 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     return _mkstemp_inner(dir, prefix, suffix, flags)
[Wed Oct 26 18:45:56.649657 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib64/python2.7/tempfile.py", line 239, in _mkstemp_inner
[Wed Oct 26 18:45:56.649659 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     fd = _os.open(file, flags, 0600)
[Wed Oct 26 18:45:56.649663 2016] [:error] [pid 14013] [remote 10.194.75.104:84] OSError: [Errno 13] Permission denied: '/var/www/movien_dev/tmp/temp/tmpBZtM0l'
[Wed Oct 26 18:45:56.649735 2016] [:error] [pid 14013] ERROR:app:Exception on /login [POST]
[Wed Oct 26 18:45:56.649738 2016] [:error] [pid 14013] Traceback (most recent call last):
[Wed Oct 26 18:45:56.649740 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Oct 26 18:45:56.649741 2016] [:error] [pid 14013]     response = self.full_dispatch_request()
[Wed Oct 26 18:45:56.649743 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Oct 26 18:45:56.649744 2016] [:error] [pid 14013]     rv = self.handle_user_exception(e)
[Wed Oct 26 18:45:56.649746 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Oct 26 18:45:56.649747 2016] [:error] [pid 14013]     reraise(exc_type, exc_value, tb)
[Wed Oct 26 18:45:56.649749 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Oct 26 18:45:56.649750 2016] [:error] [pid 14013]     rv = self.dispatch_request()
[Wed Oct 26 18:45:56.649751 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Oct 26 18:45:56.649753 2016] [:error] [pid 14013]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Oct 26 18:45:56.649755 2016] [:error] [pid 14013]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 500, in decorated
[Wed Oct 26 18:45:56.649756 2016] [:error] [pid 14013]     return f(*args, **kwargs)
[Wed Oct 26 18:45:56.649757 2016] [:error] [pid 14013]   File "/var/www/movien_dev/app/views.py", line 44, in login
[Wed Oct 26 18:45:56.649759 2016] [:error] [pid 14013]     return oid.try_login(form.openid.data, ask_for=['nickname', 'email'])
[Wed Oct 26 18:45:56.649760 2016] [:error] [pid 14013]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 561, in try_login
[Wed Oct 26 18:45:56.649762 2016] [:error] [pid 14013]     auth_request = consumer.begin(identity_url)
[Wed Oct 26 18:45:56.649763 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 353, in begin
[Wed Oct 26 18:45:56.649765 2016] [:error] [pid 14013]     return self.beginWithoutDiscovery(service, anonymous)
[Wed Oct 26 18:45:56.649766 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 376, in beginWithoutDiscovery
[Wed Oct 26 18:45:56.649768 2016] [:error] [pid 14013]     auth_req = self.consumer.begin(service)
[Wed Oct 26 18:45:56.649769 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 598, in begin
[Wed Oct 26 18:45:56.649771 2016] [:error] [pid 14013]     assoc = self._getAssociation(service_endpoint)
[Wed Oct 26 18:45:56.649772 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 1163, in _getAssociation
[Wed Oct 26 18:45:56.649774 2016] [:error] [pid 14013]     self.store.storeAssociation(endpoint.server_url, assoc)
[Wed Oct 26 18:45:56.649775 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 212, in storeAssociation
[Wed Oct 26 18:45:56.649777 2016] [:error] [pid 14013]     tmp_file, tmp = self._mktemp()
[Wed Oct 26 18:45:56.649778 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 173, in _mktemp
[Wed Oct 26 18:45:56.649779 2016] [:error] [pid 14013]     fd, name = mkstemp(dir=self.temp_dir)
[Wed Oct 26 18:45:56.649781 2016] [:error] [pid 14013]   File "/usr/lib64/python2.7/tempfile.py", line 304, in mkstemp
[Wed Oct 26 18:45:56.649782 2016] [:error] [pid 14013]     return _mkstemp_inner(dir, prefix, suffix, flags)
[Wed Oct 26 18:45:56.649784 2016] [:error] [pid 14013]   File "/usr/lib64/python2.7/tempfile.py", line 239, in _mkstemp_inner
[Wed Oct 26 18:45:56.649789 2016] [:error] [pid 14013]     fd = _os.open(file, flags, 0600)
[Wed Oct 26 18:45:56.649791 2016] [:error] [pid 14013] OSError: [Errno 13] Permission denied: '/var/www/movien_dev/tmp/temp/tmpBZtM0l'
[Wed Oct 26 18:48:46.347023 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 18:48:46.347052 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 18:48:47.932447 2016] [:error] [pid 14013] [remote 10.194.75.104:84] [2016-10-26 18:48:47,932] ERROR in app: Exception on /login [POST]
[Wed Oct 26 18:48:47.932472 2016] [:error] [pid 14013] [remote 10.194.75.104:84] Traceback (most recent call last):
[Wed Oct 26 18:48:47.932474 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Oct 26 18:48:47.932476 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     response = self.full_dispatch_request()
[Wed Oct 26 18:48:47.932478 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Oct 26 18:48:47.932480 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     rv = self.handle_user_exception(e)
[Wed Oct 26 18:48:47.932481 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Oct 26 18:48:47.932483 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     reraise(exc_type, exc_value, tb)
[Wed Oct 26 18:48:47.932485 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Oct 26 18:48:47.932486 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     rv = self.dispatch_request()
[Wed Oct 26 18:48:47.932488 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Oct 26 18:48:47.932489 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Oct 26 18:48:47.932491 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 500, in decorated
[Wed Oct 26 18:48:47.932493 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     return f(*args, **kwargs)
[Wed Oct 26 18:48:47.932494 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/var/www/movien_dev/app/views.py", line 44, in login
[Wed Oct 26 18:48:47.932496 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     return oid.try_login(form.openid.data, ask_for=['nickname', 'email'])
[Wed Oct 26 18:48:47.932498 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 561, in try_login
[Wed Oct 26 18:48:47.932499 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     auth_request = consumer.begin(identity_url)
[Wed Oct 26 18:48:47.932501 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 353, in begin
[Wed Oct 26 18:48:47.932502 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     return self.beginWithoutDiscovery(service, anonymous)
[Wed Oct 26 18:48:47.932504 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 376, in beginWithoutDiscovery
[Wed Oct 26 18:48:47.932506 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     auth_req = self.consumer.begin(service)
[Wed Oct 26 18:48:47.932507 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 598, in begin
[Wed Oct 26 18:48:47.932509 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     assoc = self._getAssociation(service_endpoint)
[Wed Oct 26 18:48:47.932524 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 1163, in _getAssociation
[Wed Oct 26 18:48:47.932526 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     self.store.storeAssociation(endpoint.server_url, assoc)
[Wed Oct 26 18:48:47.932527 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 212, in storeAssociation
[Wed Oct 26 18:48:47.932529 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     tmp_file, tmp = self._mktemp()
[Wed Oct 26 18:48:47.932530 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 173, in _mktemp
[Wed Oct 26 18:48:47.932532 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     fd, name = mkstemp(dir=self.temp_dir)
[Wed Oct 26 18:48:47.932534 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib64/python2.7/tempfile.py", line 304, in mkstemp
[Wed Oct 26 18:48:47.932535 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     return _mkstemp_inner(dir, prefix, suffix, flags)
[Wed Oct 26 18:48:47.932537 2016] [:error] [pid 14013] [remote 10.194.75.104:84]   File "/usr/lib64/python2.7/tempfile.py", line 239, in _mkstemp_inner
[Wed Oct 26 18:48:47.932538 2016] [:error] [pid 14013] [remote 10.194.75.104:84]     fd = _os.open(file, flags, 0600)
[Wed Oct 26 18:48:47.932540 2016] [:error] [pid 14013] [remote 10.194.75.104:84] OSError: [Errno 13] Permission denied: '/var/www/movien_dev/tmp/temp/tmpo9BmmG'
[Wed Oct 26 18:48:47.932609 2016] [:error] [pid 14013] ERROR:app:Exception on /login [POST]
[Wed Oct 26 18:48:47.932612 2016] [:error] [pid 14013] Traceback (most recent call last):
[Wed Oct 26 18:48:47.932614 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Oct 26 18:48:47.932615 2016] [:error] [pid 14013]     response = self.full_dispatch_request()
[Wed Oct 26 18:48:47.932617 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Oct 26 18:48:47.932619 2016] [:error] [pid 14013]     rv = self.handle_user_exception(e)
[Wed Oct 26 18:48:47.932620 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Oct 26 18:48:47.932622 2016] [:error] [pid 14013]     reraise(exc_type, exc_value, tb)
[Wed Oct 26 18:48:47.932623 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Oct 26 18:48:47.932624 2016] [:error] [pid 14013]     rv = self.dispatch_request()
[Wed Oct 26 18:48:47.932626 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Oct 26 18:48:47.932627 2016] [:error] [pid 14013]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Oct 26 18:48:47.932629 2016] [:error] [pid 14013]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 500, in decorated
[Wed Oct 26 18:48:47.932630 2016] [:error] [pid 14013]     return f(*args, **kwargs)
[Wed Oct 26 18:48:47.932632 2016] [:error] [pid 14013]   File "/var/www/movien_dev/app/views.py", line 44, in login
[Wed Oct 26 18:48:47.932633 2016] [:error] [pid 14013]     return oid.try_login(form.openid.data, ask_for=['nickname', 'email'])
[Wed Oct 26 18:48:47.932634 2016] [:error] [pid 14013]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 561, in try_login
[Wed Oct 26 18:48:47.932636 2016] [:error] [pid 14013]     auth_request = consumer.begin(identity_url)
[Wed Oct 26 18:48:47.932637 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 353, in begin
[Wed Oct 26 18:48:47.932639 2016] [:error] [pid 14013]     return self.beginWithoutDiscovery(service, anonymous)
[Wed Oct 26 18:48:47.932640 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 376, in beginWithoutDiscovery
[Wed Oct 26 18:48:47.932646 2016] [:error] [pid 14013]     auth_req = self.consumer.begin(service)
[Wed Oct 26 18:48:47.932648 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 598, in begin
[Wed Oct 26 18:48:47.932649 2016] [:error] [pid 14013]     assoc = self._getAssociation(service_endpoint)
[Wed Oct 26 18:48:47.932651 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 1163, in _getAssociation
[Wed Oct 26 18:48:47.932652 2016] [:error] [pid 14013]     self.store.storeAssociation(endpoint.server_url, assoc)
[Wed Oct 26 18:48:47.932654 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 212, in storeAssociation
[Wed Oct 26 18:48:47.932655 2016] [:error] [pid 14013]     tmp_file, tmp = self._mktemp()
[Wed Oct 26 18:48:47.932657 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 173, in _mktemp
[Wed Oct 26 18:48:47.932658 2016] [:error] [pid 14013]     fd, name = mkstemp(dir=self.temp_dir)
[Wed Oct 26 18:48:47.932660 2016] [:error] [pid 14013]   File "/usr/lib64/python2.7/tempfile.py", line 304, in mkstemp
[Wed Oct 26 18:48:47.932661 2016] [:error] [pid 14013]     return _mkstemp_inner(dir, prefix, suffix, flags)
[Wed Oct 26 18:48:47.932662 2016] [:error] [pid 14013]   File "/usr/lib64/python2.7/tempfile.py", line 239, in _mkstemp_inner
[Wed Oct 26 18:48:47.932664 2016] [:error] [pid 14013]     fd = _os.open(file, flags, 0600)
[Wed Oct 26 18:48:47.932665 2016] [:error] [pid 14013] OSError: [Errno 13] Permission denied: '/var/www/movien_dev/tmp/temp/tmpo9BmmG'
[Wed Oct 26 18:56:18.860396 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 18:56:18.860420 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 18:56:19.243476 2016] [:error] [pid 14013] [remote 10.194.75.104:68] [2016-10-26 18:56:19,242] ERROR in app: Exception on /login [POST]
[Wed Oct 26 18:56:19.243501 2016] [:error] [pid 14013] [remote 10.194.75.104:68] Traceback (most recent call last):
[Wed Oct 26 18:56:19.243503 2016] [:error] [pid 14013] [remote 10.194.75.104:68]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Oct 26 18:56:19.243505 2016] [:error] [pid 14013] [remote 10.194.75.104:68]     response = self.full_dispatch_request()
[Wed Oct 26 18:56:19.243507 2016] [:error] [pid 14013] [remote 10.194.75.104:68]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Oct 26 18:56:19.243509 2016] [:error] [pid 14013] [remote 10.194.75.104:68]     rv = self.handle_user_exception(e)
[Wed Oct 26 18:56:19.243510 2016] [:error] [pid 14013] [remote 10.194.75.104:68]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Oct 26 18:56:19.243512 2016] [:error] [pid 14013] [remote 10.194.75.104:68]     reraise(exc_type, exc_value, tb)
[Wed Oct 26 18:56:19.243514 2016] [:error] [pid 14013] [remote 10.194.75.104:68]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Oct 26 18:56:19.243515 2016] [:error] [pid 14013] [remote 10.194.75.104:68]     rv = self.dispatch_request()
[Wed Oct 26 18:56:19.243517 2016] [:error] [pid 14013] [remote 10.194.75.104:68]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Oct 26 18:56:19.243519 2016] [:error] [pid 14013] [remote 10.194.75.104:68]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Oct 26 18:56:19.243520 2016] [:error] [pid 14013] [remote 10.194.75.104:68]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 500, in decorated
[Wed Oct 26 18:56:19.243522 2016] [:error] [pid 14013] [remote 10.194.75.104:68]     return f(*args, **kwargs)
[Wed Oct 26 18:56:19.243523 2016] [:error] [pid 14013] [remote 10.194.75.104:68]   File "/var/www/movien_dev/app/views.py", line 44, in login
[Wed Oct 26 18:56:19.243539 2016] [:error] [pid 14013] [remote 10.194.75.104:68]     return oid.try_login(form.openid.data, ask_for=['nickname', 'email'])
[Wed Oct 26 18:56:19.243541 2016] [:error] [pid 14013] [remote 10.194.75.104:68]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 561, in try_login
[Wed Oct 26 18:56:19.243543 2016] [:error] [pid 14013] [remote 10.194.75.104:68]     auth_request = consumer.begin(identity_url)
[Wed Oct 26 18:56:19.243544 2016] [:error] [pid 14013] [remote 10.194.75.104:68]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 353, in begin
[Wed Oct 26 18:56:19.243546 2016] [:error] [pid 14013] [remote 10.194.75.104:68]     return self.beginWithoutDiscovery(service, anonymous)
[Wed Oct 26 18:56:19.243548 2016] [:error] [pid 14013] [remote 10.194.75.104:68]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 376, in beginWithoutDiscovery
[Wed Oct 26 18:56:19.243549 2016] [:error] [pid 14013] [remote 10.194.75.104:68]     auth_req = self.consumer.begin(service)
[Wed Oct 26 18:56:19.243551 2016] [:error] [pid 14013] [remote 10.194.75.104:68]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 598, in begin
[Wed Oct 26 18:56:19.243553 2016] [:error] [pid 14013] [remote 10.194.75.104:68]     assoc = self._getAssociation(service_endpoint)
[Wed Oct 26 18:56:19.243554 2016] [:error] [pid 14013] [remote 10.194.75.104:68]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 1158, in _getAssociation
[Wed Oct 26 18:56:19.243556 2016] [:error] [pid 14013] [remote 10.194.75.104:68]     assoc = self.store.getAssociation(endpoint.server_url)
[Wed Oct 26 18:56:19.243558 2016] [:error] [pid 14013] [remote 10.194.75.104:68]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 275, in getAssociation
[Wed Oct 26 18:56:19.243559 2016] [:error] [pid 14013] [remote 10.194.75.104:68]     association = self._getAssociation(full_name)
[Wed Oct 26 18:56:19.243561 2016] [:error] [pid 14013] [remote 10.194.75.104:68]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 291, in _getAssociation
[Wed Oct 26 18:56:19.243562 2016] [:error] [pid 14013] [remote 10.194.75.104:68]     assoc_file = file(filename, 'rb')
[Wed Oct 26 18:56:19.243564 2016] [:error] [pid 14013] [remote 10.194.75.104:68] IOError: [Errno 13] Permission denied: '/var/www/movien_dev/tmp/associations/https-open.login.yahooapis.com-7zqRNWhy5.EKPdEJ9.anF4sU5jI-45MNUX6548jJXiKVDu1BxgxYCZk'
[Wed Oct 26 18:56:19.243629 2016] [:error] [pid 14013] ERROR:app:Exception on /login [POST]
[Wed Oct 26 18:56:19.243632 2016] [:error] [pid 14013] Traceback (most recent call last):
[Wed Oct 26 18:56:19.243633 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Oct 26 18:56:19.243635 2016] [:error] [pid 14013]     response = self.full_dispatch_request()
[Wed Oct 26 18:56:19.243636 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Oct 26 18:56:19.243638 2016] [:error] [pid 14013]     rv = self.handle_user_exception(e)
[Wed Oct 26 18:56:19.243639 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Oct 26 18:56:19.243641 2016] [:error] [pid 14013]     reraise(exc_type, exc_value, tb)
[Wed Oct 26 18:56:19.243642 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Oct 26 18:56:19.243644 2016] [:error] [pid 14013]     rv = self.dispatch_request()
[Wed Oct 26 18:56:19.243645 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Oct 26 18:56:19.243647 2016] [:error] [pid 14013]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Oct 26 18:56:19.243648 2016] [:error] [pid 14013]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 500, in decorated
[Wed Oct 26 18:56:19.243654 2016] [:error] [pid 14013]     return f(*args, **kwargs)
[Wed Oct 26 18:56:19.243656 2016] [:error] [pid 14013]   File "/var/www/movien_dev/app/views.py", line 44, in login
[Wed Oct 26 18:56:19.243657 2016] [:error] [pid 14013]     return oid.try_login(form.openid.data, ask_for=['nickname', 'email'])
[Wed Oct 26 18:56:19.243659 2016] [:error] [pid 14013]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 561, in try_login
[Wed Oct 26 18:56:19.243660 2016] [:error] [pid 14013]     auth_request = consumer.begin(identity_url)
[Wed Oct 26 18:56:19.243662 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 353, in begin
[Wed Oct 26 18:56:19.243663 2016] [:error] [pid 14013]     return self.beginWithoutDiscovery(service, anonymous)
[Wed Oct 26 18:56:19.243665 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 376, in beginWithoutDiscovery
[Wed Oct 26 18:56:19.243666 2016] [:error] [pid 14013]     auth_req = self.consumer.begin(service)
[Wed Oct 26 18:56:19.243668 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 598, in begin
[Wed Oct 26 18:56:19.243669 2016] [:error] [pid 14013]     assoc = self._getAssociation(service_endpoint)
[Wed Oct 26 18:56:19.243671 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 1158, in _getAssociation
[Wed Oct 26 18:56:19.243672 2016] [:error] [pid 14013]     assoc = self.store.getAssociation(endpoint.server_url)
[Wed Oct 26 18:56:19.243674 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 275, in getAssociation
[Wed Oct 26 18:56:19.243675 2016] [:error] [pid 14013]     association = self._getAssociation(full_name)
[Wed Oct 26 18:56:19.243677 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 291, in _getAssociation
[Wed Oct 26 18:56:19.243678 2016] [:error] [pid 14013]     assoc_file = file(filename, 'rb')
[Wed Oct 26 18:56:19.243680 2016] [:error] [pid 14013] IOError: [Errno 13] Permission denied: '/var/www/movien_dev/tmp/associations/https-open.login.yahooapis.com-7zqRNWhy5.EKPdEJ9.anF4sU5jI-45MNUX6548jJXiKVDu1BxgxYCZk'
[Wed Oct 26 18:56:25.720986 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 18:56:25.721003 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 18:56:28.557214 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 18:56:28.557231 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 18:56:30.185811 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 18:56:30.185840 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 18:56:31.889531 2016] [:error] [pid 14013] [remote 10.194.75.104:31317] [2016-10-26 18:56:31,889] ERROR in app: Exception on /login [POST]
[Wed Oct 26 18:56:31.889557 2016] [:error] [pid 14013] [remote 10.194.75.104:31317] Traceback (most recent call last):
[Wed Oct 26 18:56:31.889559 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Oct 26 18:56:31.889561 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]     response = self.full_dispatch_request()
[Wed Oct 26 18:56:31.889563 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Oct 26 18:56:31.889564 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]     rv = self.handle_user_exception(e)
[Wed Oct 26 18:56:31.889566 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Oct 26 18:56:31.889581 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]     reraise(exc_type, exc_value, tb)
[Wed Oct 26 18:56:31.889582 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Oct 26 18:56:31.889584 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]     rv = self.dispatch_request()
[Wed Oct 26 18:56:31.889586 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Oct 26 18:56:31.889587 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Oct 26 18:56:31.889589 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 500, in decorated
[Wed Oct 26 18:56:31.889590 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]     return f(*args, **kwargs)
[Wed Oct 26 18:56:31.889592 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]   File "/var/www/movien_dev/app/views.py", line 44, in login
[Wed Oct 26 18:56:31.889593 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]     return oid.try_login(form.openid.data, ask_for=['nickname', 'email'])
[Wed Oct 26 18:56:31.889595 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 561, in try_login
[Wed Oct 26 18:56:31.889597 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]     auth_request = consumer.begin(identity_url)
[Wed Oct 26 18:56:31.889598 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 353, in begin
[Wed Oct 26 18:56:31.889600 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]     return self.beginWithoutDiscovery(service, anonymous)
[Wed Oct 26 18:56:31.889601 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 376, in beginWithoutDiscovery
[Wed Oct 26 18:56:31.889603 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]     auth_req = self.consumer.begin(service)
[Wed Oct 26 18:56:31.889605 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 598, in begin
[Wed Oct 26 18:56:31.889606 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]     assoc = self._getAssociation(service_endpoint)
[Wed Oct 26 18:56:31.889608 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 1163, in _getAssociation
[Wed Oct 26 18:56:31.889609 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]     self.store.storeAssociation(endpoint.server_url, assoc)
[Wed Oct 26 18:56:31.889611 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 212, in storeAssociation
[Wed Oct 26 18:56:31.889612 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]     tmp_file, tmp = self._mktemp()
[Wed Oct 26 18:56:31.889614 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 173, in _mktemp
[Wed Oct 26 18:56:31.889616 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]     fd, name = mkstemp(dir=self.temp_dir)
[Wed Oct 26 18:56:31.889617 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]   File "/usr/lib64/python2.7/tempfile.py", line 304, in mkstemp
[Wed Oct 26 18:56:31.889619 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]     return _mkstemp_inner(dir, prefix, suffix, flags)
[Wed Oct 26 18:56:31.889620 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]   File "/usr/lib64/python2.7/tempfile.py", line 239, in _mkstemp_inner
[Wed Oct 26 18:56:31.889622 2016] [:error] [pid 14013] [remote 10.194.75.104:31317]     fd = _os.open(file, flags, 0600)
[Wed Oct 26 18:56:31.889626 2016] [:error] [pid 14013] [remote 10.194.75.104:31317] OSError: [Errno 13] Permission denied: '/var/www/movien_dev/tmp/temp/tmpbQEcdl'
[Wed Oct 26 18:56:31.889687 2016] [:error] [pid 14013] ERROR:app:Exception on /login [POST]
[Wed Oct 26 18:56:31.889690 2016] [:error] [pid 14013] Traceback (most recent call last):
[Wed Oct 26 18:56:31.889691 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Oct 26 18:56:31.889693 2016] [:error] [pid 14013]     response = self.full_dispatch_request()
[Wed Oct 26 18:56:31.889694 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Oct 26 18:56:31.889696 2016] [:error] [pid 14013]     rv = self.handle_user_exception(e)
[Wed Oct 26 18:56:31.889697 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Oct 26 18:56:31.889699 2016] [:error] [pid 14013]     reraise(exc_type, exc_value, tb)
[Wed Oct 26 18:56:31.889700 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Oct 26 18:56:31.889701 2016] [:error] [pid 14013]     rv = self.dispatch_request()
[Wed Oct 26 18:56:31.889703 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Oct 26 18:56:31.889704 2016] [:error] [pid 14013]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Oct 26 18:56:31.889706 2016] [:error] [pid 14013]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 500, in decorated
[Wed Oct 26 18:56:31.889707 2016] [:error] [pid 14013]     return f(*args, **kwargs)
[Wed Oct 26 18:56:31.889709 2016] [:error] [pid 14013]   File "/var/www/movien_dev/app/views.py", line 44, in login
[Wed Oct 26 18:56:31.889710 2016] [:error] [pid 14013]     return oid.try_login(form.openid.data, ask_for=['nickname', 'email'])
[Wed Oct 26 18:56:31.889712 2016] [:error] [pid 14013]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 561, in try_login
[Wed Oct 26 18:56:31.889713 2016] [:error] [pid 14013]     auth_request = consumer.begin(identity_url)
[Wed Oct 26 18:56:31.889715 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 353, in begin
[Wed Oct 26 18:56:31.889716 2016] [:error] [pid 14013]     return self.beginWithoutDiscovery(service, anonymous)
[Wed Oct 26 18:56:31.889717 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 376, in beginWithoutDiscovery
[Wed Oct 26 18:56:31.889719 2016] [:error] [pid 14013]     auth_req = self.consumer.begin(service)
[Wed Oct 26 18:56:31.889720 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 598, in begin
[Wed Oct 26 18:56:31.889722 2016] [:error] [pid 14013]     assoc = self._getAssociation(service_endpoint)
[Wed Oct 26 18:56:31.889723 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 1163, in _getAssociation
[Wed Oct 26 18:56:31.889725 2016] [:error] [pid 14013]     self.store.storeAssociation(endpoint.server_url, assoc)
[Wed Oct 26 18:56:31.889726 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 212, in storeAssociation
[Wed Oct 26 18:56:31.889728 2016] [:error] [pid 14013]     tmp_file, tmp = self._mktemp()
[Wed Oct 26 18:56:31.889729 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 173, in _mktemp
[Wed Oct 26 18:56:31.889731 2016] [:error] [pid 14013]     fd, name = mkstemp(dir=self.temp_dir)
[Wed Oct 26 18:56:31.889732 2016] [:error] [pid 14013]   File "/usr/lib64/python2.7/tempfile.py", line 304, in mkstemp
[Wed Oct 26 18:56:31.889734 2016] [:error] [pid 14013]     return _mkstemp_inner(dir, prefix, suffix, flags)
[Wed Oct 26 18:56:31.889738 2016] [:error] [pid 14013]   File "/usr/lib64/python2.7/tempfile.py", line 239, in _mkstemp_inner
[Wed Oct 26 18:56:31.889740 2016] [:error] [pid 14013]     fd = _os.open(file, flags, 0600)
[Wed Oct 26 18:56:31.889741 2016] [:error] [pid 14013] OSError: [Errno 13] Permission denied: '/var/www/movien_dev/tmp/temp/tmpbQEcdl'
[Wed Oct 26 18:58:08.421027 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 18:58:08.421045 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 18:58:11.644762 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 18:58:11.644785 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 18:58:12.032999 2016] [:error] [pid 14013] [remote 10.194.75.104:31573] [2016-10-26 18:58:12,032] ERROR in app: Exception on /login [POST]
[Wed Oct 26 18:58:12.033025 2016] [:error] [pid 14013] [remote 10.194.75.104:31573] Traceback (most recent call last):
[Wed Oct 26 18:58:12.033027 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Oct 26 18:58:12.033029 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]     response = self.full_dispatch_request()
[Wed Oct 26 18:58:12.033030 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Oct 26 18:58:12.033032 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]     rv = self.handle_user_exception(e)
[Wed Oct 26 18:58:12.033034 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Oct 26 18:58:12.033035 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]     reraise(exc_type, exc_value, tb)
[Wed Oct 26 18:58:12.033037 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Oct 26 18:58:12.033038 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]     rv = self.dispatch_request()
[Wed Oct 26 18:58:12.033040 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Oct 26 18:58:12.033042 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Oct 26 18:58:12.033043 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 500, in decorated
[Wed Oct 26 18:58:12.033045 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]     return f(*args, **kwargs)
[Wed Oct 26 18:58:12.033046 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]   File "/var/www/movien_dev/app/views.py", line 44, in login
[Wed Oct 26 18:58:12.033048 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]     return oid.try_login(form.openid.data, ask_for=['nickname', 'email'])
[Wed Oct 26 18:58:12.033049 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 561, in try_login
[Wed Oct 26 18:58:12.033051 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]     auth_request = consumer.begin(identity_url)
[Wed Oct 26 18:58:12.033053 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 353, in begin
[Wed Oct 26 18:58:12.033054 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]     return self.beginWithoutDiscovery(service, anonymous)
[Wed Oct 26 18:58:12.033056 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 376, in beginWithoutDiscovery
[Wed Oct 26 18:58:12.033069 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]     auth_req = self.consumer.begin(service)
[Wed Oct 26 18:58:12.033071 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 598, in begin
[Wed Oct 26 18:58:12.033073 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]     assoc = self._getAssociation(service_endpoint)
[Wed Oct 26 18:58:12.033074 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 1158, in _getAssociation
[Wed Oct 26 18:58:12.033076 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]     assoc = self.store.getAssociation(endpoint.server_url)
[Wed Oct 26 18:58:12.033077 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 275, in getAssociation
[Wed Oct 26 18:58:12.033079 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]     association = self._getAssociation(full_name)
[Wed Oct 26 18:58:12.033081 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 291, in _getAssociation
[Wed Oct 26 18:58:12.033082 2016] [:error] [pid 14013] [remote 10.194.75.104:31573]     assoc_file = file(filename, 'rb')
[Wed Oct 26 18:58:12.033084 2016] [:error] [pid 14013] [remote 10.194.75.104:31573] IOError: [Errno 13] Permission denied: '/var/www/movien_dev/tmp/associations/https-open.login.yahooapis.com-7zqRNWhy5.EKPdEJ9.anF4sU5jI-45MNUX6548jJXiKVDu1BxgxYCZk'
[Wed Oct 26 18:58:12.033161 2016] [:error] [pid 14013] ERROR:app:Exception on /login [POST]
[Wed Oct 26 18:58:12.033167 2016] [:error] [pid 14013] Traceback (most recent call last):
[Wed Oct 26 18:58:12.033169 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
[Wed Oct 26 18:58:12.033170 2016] [:error] [pid 14013]     response = self.full_dispatch_request()
[Wed Oct 26 18:58:12.033172 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
[Wed Oct 26 18:58:12.033173 2016] [:error] [pid 14013]     rv = self.handle_user_exception(e)
[Wed Oct 26 18:58:12.033175 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
[Wed Oct 26 18:58:12.033176 2016] [:error] [pid 14013]     reraise(exc_type, exc_value, tb)
[Wed Oct 26 18:58:12.033178 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
[Wed Oct 26 18:58:12.033179 2016] [:error] [pid 14013]     rv = self.dispatch_request()
[Wed Oct 26 18:58:12.033180 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
[Wed Oct 26 18:58:12.033182 2016] [:error] [pid 14013]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Oct 26 18:58:12.033183 2016] [:error] [pid 14013]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 500, in decorated
[Wed Oct 26 18:58:12.033185 2016] [:error] [pid 14013]     return f(*args, **kwargs)
[Wed Oct 26 18:58:12.033186 2016] [:error] [pid 14013]   File "/var/www/movien_dev/app/views.py", line 44, in login
[Wed Oct 26 18:58:12.033188 2016] [:error] [pid 14013]     return oid.try_login(form.openid.data, ask_for=['nickname', 'email'])
[Wed Oct 26 18:58:12.033190 2016] [:error] [pid 14013]   File "/usr/lib64/python2.7/site-packages/flask_openid.py", line 561, in try_login
[Wed Oct 26 18:58:12.033193 2016] [:error] [pid 14013]     auth_request = consumer.begin(identity_url)
[Wed Oct 26 18:58:12.033195 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 353, in begin
[Wed Oct 26 18:58:12.033198 2016] [:error] [pid 14013]     return self.beginWithoutDiscovery(service, anonymous)
[Wed Oct 26 18:58:12.033200 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 376, in beginWithoutDiscovery
[Wed Oct 26 18:58:12.033209 2016] [:error] [pid 14013]     auth_req = self.consumer.begin(service)
[Wed Oct 26 18:58:12.033212 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 598, in begin
[Wed Oct 26 18:58:12.033214 2016] [:error] [pid 14013]     assoc = self._getAssociation(service_endpoint)
[Wed Oct 26 18:58:12.033216 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/consumer/consumer.py", line 1158, in _getAssociation
[Wed Oct 26 18:58:12.033219 2016] [:error] [pid 14013]     assoc = self.store.getAssociation(endpoint.server_url)
[Wed Oct 26 18:58:12.033221 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 275, in getAssociation
[Wed Oct 26 18:58:12.033224 2016] [:error] [pid 14013]     association = self._getAssociation(full_name)
[Wed Oct 26 18:58:12.033226 2016] [:error] [pid 14013]   File "/usr/lib/python2.7/site-packages/openid/store/filestore.py", line 291, in _getAssociation
[Wed Oct 26 18:58:12.033229 2016] [:error] [pid 14013]     assoc_file = file(filename, 'rb')
[Wed Oct 26 18:58:12.033231 2016] [:error] [pid 14013] IOError: [Errno 13] Permission denied: '/var/www/movien_dev/tmp/associations/https-open.login.yahooapis.com-7zqRNWhy5.EKPdEJ9.anF4sU5jI-45MNUX6548jJXiKVDu1BxgxYCZk'
[Wed Oct 26 19:01:13.726204 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 19:01:13.726222 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 19:01:16.064025 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 19:01:16.064050 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 19:01:27.781234 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 19:01:27.781259 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 19:05:10.902016 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 19:05:10.902042 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 19:05:11.539301 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 19:05:11.539321 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 19:05:20.969026 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 19:05:20.969043 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 19:05:24.102912 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 19:05:24.102935 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 19:05:57.087477 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 19:05:57.087495 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 19:06:39.748670 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 19:06:39.748692 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 19:06:42.316264 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 19:06:42.316293 2016] [:error] [pid 14013]   form = LoginForm()
[Wed Oct 26 19:06:46.583773 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Wed Oct 26 19:06:46.583797 2016] [:error] [pid 14013]   form = LoginForm()
[Thu Oct 27 16:19:51.796572 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Thu Oct 27 16:19:51.796592 2016] [:error] [pid 14013]   form = LoginForm()
[Thu Oct 27 16:49:10.710831 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Thu Oct 27 16:49:10.710847 2016] [:error] [pid 14013]   form = LoginForm()
[Thu Oct 27 22:53:26.305850 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Thu Oct 27 22:53:26.305888 2016] [:error] [pid 14013]   form = LoginForm()
[Thu Oct 27 23:00:26.102174 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Thu Oct 27 23:00:26.102203 2016] [:error] [pid 14013]   form = LoginForm()
[Fri Oct 28 13:33:28.738899 2016] [:error] [pid 14013] /var/www/movien_dev/app/views.py:40: FlaskWTFDeprecationWarning: "flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in 1.0.
[Fri Oct 28 13:33:28.738931 2016] [:error] [pid 14013]   form = LoginForm()
